spring:
  profiles:
    active: dev

provider:
  name: demo-provider

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://test.toutiao.im:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: demo-consumer
  profiles: test
feign:
  hystrix:
    enabled: true

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: demo-consumer
  profiles: dev
feign:
  hystrix:
    enabled: true