server:
  port: 8762

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/javahongxi/whatsmars/
          searchPaths: whatsmars-spring-cloud/configfile
          username: javahongxi
          password: jd854749
      label: master